baseurl = "https://www.rasikjain.com"
title = "Rasik Jain - Software Engineer | Consulting"


theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[params]
    author = "Rasik Jain"
    info = "Software Engineer and Enterprise Architect - ReactJS | C# | AWS"
    subInfo = "Product Development, Consulting, Software Engineering, Solution & Enterprise Architecture, Agile/Scrum, Full-Stack, Cloud Computing & Data Analytics."
    metaDescription = "Rasik Jain - Experienced Software engineer and Enterprise Architect. Providing consulting services with focus on full-stack, Javascript, ReactJS, C#, AWS Cloud and Cyber Security."
    metaKeywords = "technology, full stack, javascript, reactjs, c#, cloud, aws, cyber security, node.js, .net core, enterprise architecture, startups, consulting, remote, freelancing, blog, developer, personal"
    avatarurl = "images/avatar_rasik.jpg"
    footercontent = ""
    hometitle = "Rasik Jain - Software Engineer | Full-Stack | ReactJS | C# | AWS"
    headertitle = "Rasik Jain"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []


[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/jainrasik/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/rasikjain/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/rasikjain/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/1993944/rasik-jain"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 5
    url = "/contact/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Rasik Jain - Software Engineer | Consulting"
        
        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Rasik Jain"
        info = "Software Engineer and Enterprise Architect - ReactJS | C# | AWS"
        subInfo = "Product Development, Consulting, Software Engineering, Solution & Enterprise Architecture, Agile/Scrum, Full-Stack, Cloud Computing & Data Analytics."
        metaDescription = "Rasik Jain - Experienced Software engineer and Enterprise Architect. Providing consulting services with focus on full-stack, Javascript, ReactJS, C#, AWS Cloud and Cyber Security."
        metaKeywords = "technology, full stack, javascript, reactjs, c#, cloud, aws, cyber security, node.js, .net core, enterprise architecture, startups, consulting, remote, freelancing, blog, developer, personal"
        hometitle = "Rasik Jain - Software Engineer | Full-Stack | ReactJS | C# | AWS"
        headertitle = "Rasik Jain"
        hideCopyright = false
        hideCredits = false

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1.0
        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 4.0
        url = "/contact/"


    