baseurl = "https://www.rasikjain.com"
title = "Rasik Jain - Software Engineer | Consulting"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

googleAnalytics = "UA-8667481-1"
enableRobotsTXT = false


[params]
    author = "Rasik Jain"
    description = "Rasik Jain - Experienced Software engineer and Enterprise Architect. Providing consulting services with focus on full-stack, Javascript, ReactJS, C#, AWS Cloud and Cyber Security."    
    keywords = "technology, full stack, javascript, reactjs, c#, cloud, aws, cyber security, node.js, .net core, enterprise architecture, startups, consulting, remote, freelancing, blog, developer, personal"
    info = "AI / ML and Full-Stack Engineer "
    subInfo = "Gen AI | LLM | RAG Pipelines | LangChain | Tensorflow | NumPy | Pandas | Jupyter | Python | React | JavaScript | Cloud"
    avatarurl = "images/avatar_rasik.jpg"
    #gravatar = "jainrasik@gmail.com"
    footercontent = ""
    hometitle = "Rasik Jain - Software Engineer | Gen AI | ML | Full-Stack | Python | React | Node.js | Javascript | AWS"
    headertitle = "Rasik Jain"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

    # Google Analytics 4
    googleAnalyticsID = "G-821HSLZZ5Y"

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 15

    # Enable 

    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params.hire]
    isactive = true
    title = "( Open to Opportunities )"
    url = "/about/"
    
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/jainrasik/"
    title = "@jainrasik - Twitter"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/rasikjain/"
    title = "@rasikjain - LinkedIn"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/rasikjain/"
    title = "@rasikjain - Github"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/1993944/rasik-jain"
    title = "rasik-jain - Stackoverlfow"
[[params.social]]
    name = "Email"
    icon = "far fa-envelope"
    weight = 5
    url = "mailto:jainrasik@gmail.com?subject=Hello,%20Regarding%20your%20profile, source:rasikjain.com"
    title = "jainrasik@gmail.com"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://www.rasikjain.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 5
    url = "/contact/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        
        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Rasik Jain"
        info = "AI / ML and Full-Stack Engineer "
        subInfo = "Generative AI ㆍ ML ㆍ LLM ㆍ RAG ㆍ AI Agents ㆍ Tensorflow ㆍ NumPy ㆍ Pandas ㆍ Jupyter ㆍ Python ㆍ React ㆍ JavaScript ㆍ Cloud"
        subInfo2 = "Software Engineer with expertise in AI and ML, delivering intelligent, scalable, and secure solutions that integrate modern web development with data-driven insights."
        metaDescription = "Rasik Jain - Experienced Gen AI / ML Full-Stack Software engineer and Enterprise Architect. Providing consulting services with focus on Gen AI, LLM, RAG Pipelines, LangChain, TensorFlow, NumPy, Pandas, Jupyter, Python, React, JavaScript and Cloud."
        metaKeywords = "Gen AI, ML, Artificial Intelligence, Machine Learning, LLM, LangChain, Rag Piplines, AI Agents, Jupyter, NumPy, Pandas, AWS, fullstack, full-stack, javascript, React, TypeScript, GraphQL, cloud, aws, cyber security, node.js, enterprise architecture, startups, consulting, remote, freelancing, blog, developer, personal"
        hometitle = "Rasik Jain - Software Engineer | Gen AI | ML | AI Agents | Full-Stack | Python | React | Node.js | Javascript | AWS"

        hideCopyright = false     
        hideCredits = false

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1.0
        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Resume"
        weight = 2.5
        url = "/resume/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 4.0
        url = "/contact/"


    
